### PR TITLE
Spike client for verifiable map

### PR DESCRIPTION
**Pull request by michaelabenyohai**
Take a key, value and proof from a verifiable map for that key and verify whether or not that value is the latest for that key in that map. This is a spike.

### CODE REVIEW

**Comment by philandstuff** [comment]
how do I try it out? this is what I tried:

```
$ ./integritytool/runner.py
> mth
Traceback (most recent call last):
  File "./integritytool/runner.py", line 113, in <module>
    ReplCmd().cmdloop()
  File "/opt/boxen/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "./integritytool/runner.py", line 30, in do_mth
    self.runner.compute_root_hash()
  File "./integritytool/runner.py", line 75, in compute_root_hash
    with open('entries.json') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'entries.json'
```

**Comment by michaelabenyohai** [comment]
@philandstuff this should work now, as you tried it previously.

**Comment by philandstuff** [comment]
okay, I'll try it when i've got my normal laptop again

**Comment by philandstuff** [comment]
I got a bit further this time:

```
$ ./integritytool/runner.py
> mth
{'entries': [{'extra_data': '',
              'leaf_input': 'AAAAAAFSjeCvzYAAAAAUeyAidGhpbmciOiAic3R1ZmYiIH0AAA=='},
             {'extra_data': '',
              'leaf_input': 'AAAAAAFSjkWqs4AAAAAleyAiaHVoLCBubyBjYm9yPyA6KSI6ICJub3BlLCBub25lISIgfQAA'},
             {'extra_data': '',
              'leaf_input': 'AAAAAAFSknZ5SYAAAAAQeyAib25lIjogInR3byIgfQAA'}]}
b'SndjhdTT3KYbbiSR12MCAuEALcAXzIK7V1cnTe4csQk='
> mapth
Traceback (most recent call last):
  File "./integritytool/runner.py", line 113, in <module>
    ReplCmd().cmdloop()
  File "/opt/boxen/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "./integritytool/runner.py", line 34, in do_mapth
    key, value, proof = arg.split(' ')
ValueError: need more than 1 value to unpack
```

let's meet IRL to talk it over

**Comment by michaelabenyohai** [comment]
This exception was due to there not being the correct number of arguments for the mapth function. I've made another commit to print Help for a function if the incorrect number of arguments are supplied.

The mapth function takes the key, value and 'record proof'. An example is `mapth a 2 ['q1BN5wwrHEONK2qXNLgp1pJh8QbeyvHlczCmEa6rphQ=',255]` where `key=a`, `value=2` and `proof=['q1BN5wwrHEONK2qXNLgp1pJh8QbeyvHlczCmEa6rphQ=',255]`. This should give you `Map tree hash: b'2rAZz4HJAMJqJ5c8ClS4wEzTP71GTdjMZMe1rKWPA5o='` - I obtained this tree hash for the verifiable map from the demo in the CT repo (`/python/demo/vdb`).

**Pull request closed without merging**
